### ISSUE TITLE
Is it possible to terminate long running process?

### ISSUE THREAD

**Issue by gitreagan** [Tewr/BlazorWorker#15]
Hi,
I have a long running task in an external dll, which takes more than 30 secs to complete. We track the UI changes while the task is running and need to terminate the running task if the input values changed, and start the task again with the new values. Tried calling the DisposeAsync method but it seems to be not working as we needed. Is there a better way to achieve this using BlazorWorker? Thank you!

`await backgroundService.DisposeAsync();
await worker.DisposeAsync();`

**Comment by Tewr** [comment]
`worker.DisposeAsync()` is supposed to abrubtly kill the worker. If that's not working there is probably a bug. Your use case is probably common so I'll write up an example in the demo project and I'll re-test it at the same time.

No point in disposing the service first, also that probably won't work as the notion of service is inside the process, which is single threaded, and thus can't head the call if it's busy running your code.

**Comment by gitreagan** [comment]
Thank you Tewr!

**Comment by Tewr** [comment]
`worker.DisposeAsync()` works just fine. 

However implementation of cancellation without killing the worker turned out trickier than I thought. Can't just write classic .net code as we are single-threaded.
The synchronisation context behaviour in mono-wasm is not working as I expected.

In any case I found there are some missing pieces in the library here, like service methods with async signature. Perhaps built-in support for cancellation token. It's an interesting use case, that's for sure.

**Comment by gitreagan** [comment]
You are right Tewr, worker.DisposeAsync() works fine. I was disposing the service first, which was giving errors.

Yes, killing the running worker seems to be challenging. We have decided to wait till the process is complete and re-run the task with new inputs. Please advice if you can think of a better way to achieve our needs. Thanks again!

**Comment by Tewr** [comment]
I've managed to get this to work, but gets it's messy as #16 has not been implemented. You have to yield at some point so that the context gets the chance to read an incoming message which sets a flag somewhere that you can read to cancel the operation. Yielding has a hefty performance penality, so you can't yield in every loop, you have to find some delta that works for you. Works with `await Task.Delay(100)`, Task.Delay(1) does not seem to work, this is what confused me at first. Not sure where the magic limit is yet.

**Comment by gitreagan** [comment]
Ok will try it. Thank you!

**Comment by Tewr** [comment]
I've published the example [here](https://github.com/Tewr/BlazorWorker/blob/136a9a60013d3463745c2d970aee4b5ad4772999/src/BlazorWorker.Demo/Client/Pages/Cancellation.razor), also lots of changes [in service](https://github.com/Tewr/BlazorWorker/blob/136a9a60013d3463745c2d970aee4b5ad4772999/src/BlazorWorker.Demo/Shared/MathsService.cs).

This example shows that its feasable in the current state of things, but messy with a lot of bloat. The whole CancellationToken might be a tad overkill, but like a natural follow-up on supporting Tasks, I think they should probably be supported by the library as well.

Finally, `Task.Delay(1)` works fine for yielding. I must have done something else wrong yesterday.

**Comment by gitreagan** [comment]
Will try this, thank you Tewr!
