### ISSUE TITLE
Http call inside a worker service

### ISSUE THREAD

**Issue by mertkokusen** [Tewr/BlazorWorker#17]
Is it possible to make an http request inside the worker service? It seems the worker service can't get created if I put a HttpClient property in it, although I don't see any error messages anywhere. I tried to explicitly pull in System.Net.Http.dll with worker init options but still it's failing silently.

**Comment by Tewr** [comment]
Should be possible, but 
- I've never tried it
- no built in support for creating an httpclient instance.

Do do this, you should probably look at the implementation of the setup code in blazor for builder.addhttpclient and do something similar.

**Comment by mertkokusen** [comment]
I managed to make it work (not with injection but with creating the client manually). The reason it didn't work turned out to be mostly my fault. I needed to pull in "System.Net.Http.dll" and "System.Net.Http.WebAssemblyHttpHandler.dll".  But I think it would be nice to see some error message in the console if a dependency can't be found at runtime, is it possible? Because I also had problems with dependencies of my service's dependencies and it's not always clear what is missing. 

I also saw a method in the code "GuessReferencedDlls", but it seems like it's not being used at all. It seems like it would make everything much easier, is there any reason to not use this?

And finally, thank you for this amazing work :)

**Comment by Tewr** [comment]
That's great! 

> But I think it would be nice to see some error message in the console if a dependency can't be found at runtime
I think I kind of blanket-excluded all debug messaging but I'd certainly _expect_ this to throw an exception. On the other hand, it turns out it "depends" -- several times I've had an explicit "you are missing this dll" message, and sometimes, the experience is what you are describing - silence from the framework. Possibly I could use the static event for loading missing assemblies to throw. And possible I'm swallowing the message at some point but I have very few try-catch clauses and none of them, to my knowledge, is without output.

I think a solution to this could be either always listening to `AppDomain.AssemblyResolve`, or maybe expose a setup option to activate it.

As for _GuessReferencedDlls_ - it currently does its job far to well. If you try it out, youll see that any call will end up listing hundreds of assemblies most of the time - most of them which does not exist. The real solution is to replace GuessReferencedDlls with something sophisticated and build-time. Like blazor does - dumping all references in a json. It's out of my league (I have near zero experience with Roslyn et al, I do know a tad of msbuild). But I intend to look in to this in the future.

**Comment by mertkokusen** [comment]
> I think a solution to this could be either always listening to AppDomain.AssemblyResolve, or maybe expose a setup option to activate it.

This would be awesome. 

How about loading all the assemblies in blazor.boot.json? We are already referencing the service dll in the blazor client app and this way blazor figures out the dependencies for us. Including Http namespaces :)

**Comment by Tewr** [comment]
> How about loading all the assemblies in blazor.boot.json?

I started out like that at first, sure it's a brute force approach that "just works". However what we are not interested in is the assemblies of blazor itself, and they have a quite significant impact on load time and ram. 

Explicitly naming the blazor dlls and loading everything except them could work, but then could break if someone actually want to use something inside of them... There is possibly some middle-ground here of course, and there is always the possibility of opting in for a simpler setup experience in exchange for ram and load time.

In any case, I'll go for the augmented logging of missing dlls first, and I'll see where that leads us..

**Comment by mertkokusen** [comment]
I agree that it is a bit waste of resources. Having adequate logging for dependency errors should be sufficient.

**Comment by Tewr** [comment]
@mertkokusen Could you share some of the setup code that failed for you?
I `do `get an error message, when trying to initialize HttpClient, although not very explicit: 

**My service class:**
```
 public class WebCallerService
    {
        public HttpClient HttpClient { get; }

        public WebCallerService()
        {
            HttpClient = new HttpClient();
        }

        public async Task<string> CallGitHubApi()
        {
            var github = await HttpClient.GetAsync("https://api.github.com");
            return await github.Content.ReadAsStringAsync();
        }
    }
```

**Caller code in .razor file**:

```
          try {
                output = $"{rn}{LogDate()} Creating background service...";
                StateHasChanged();

                sw.Start();
                backgroundService = await worker.CreateBackgroundServiceAsync<WebCallerService>();
        }
        catch (Exception e)
        {
            output += $"{rn}Error = {e}";
        }
```

**Output**:
17:58:45:975 Creating background service...
Error = System.TypeLoadException: Could not load type of field 'BlazorWorker.Demo.Shared.WebCallerService:<HttpClient>k__BackingField' (0) due to: Could not resolve type with token 01000023 from typeref (expected class 'System.Net.Http.HttpClient' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Net.Http.HttpClient member:(null)
  at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceProxy`1[T].InitAsync (BlazorWorker.Core.WorkerInitOptions workerInitOptions) [0x004ce] in C:\Users\Tor\source\repos\BlazorWorker\src\BlazorWorker.ServiceFactory\WorkerBackgroundServiceProxy.cs:141 
  at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceExtensions.CreateBackgroundServiceAsync[T] (BlazorWorker.Core.IWorker webWorkerProxy, BlazorWorker.Core.WorkerInitOptions workerInitOptions) [0x0008f] in C:\Users\Tor\source\repos\BlazorWorker\src\BlazorWorker.ServiceFactory\WorkerBackgroundServiceExtensions.cs:23 
  at BlazorWorker.Demo.Client.Pages.Http.OnClick (System.EventArgs _) [0x0016a] in C:\Users\Tor\source\repos\BlazorWorker\src\BlazorWorker.Demo\Client\Pages\Http.razor:53 

Are you saying you never did "new HttpClient()" at first when you didnt get any error?

**Comment by Tewr** [comment]
hmm i think what could be interesting is your program.cs

**Comment by mertkokusen** [comment]
Just putting a property with type HttpClient is enough you don't have to instantiate it. Then it won't log anything to the console except 
`﻿WorkerBackgroundServiceProxy.InitAsync(): 1 {"WorkerId":1,"InstanceId":1,"AssemblyName":"LoadStationWorkerService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","TypeName":"LoadStationWorkerService.LSInteropService","CallId":0,"MessageType":"InitInstance"}`

And then I provide these dependencies "System.Net.Http.dll","System.Net.Http.WebAssemblyHttpHandler.dll" and it works. But I never surrounded CreateBackgroundServiceAsync with a try-catch if I did maybe I would see the TypeLoadException. 

I have nothing special in my program.cs. It's just standard blazer template with the single added line
`builder.Services.AddWorkerFactory();`

**Comment by Tewr** [comment]
Ok thanks for the quick info. Some further investigation showed that I got this error before doing "new httpclient". I've been turning this around and about for a while and I'm quite happy with the current exceptions being thrown -- but I will still go ahead and add a console log for the `AppDomain.AssemblyResolve` event - it contains exactly the info needed, and it's not really possible today for library consumers to easily add the event, as declaring it in a service is too late.

**Comment by ljcollins25** [comment]
Would it be possible to just load the assemblies lazily rather than raising an error? Blazor seems to have this ability, but it would require pulling over the necessary JS into the worker.
https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-6.0

https://source.dot.net/#Microsoft.AspNetCore.Components.WebAssembly/Services/LazyAssemblyLoader.cs,b629af500e6b7422
