### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by andersson09** [Tewr/BlazorWorker#32]
Hi, great work.

Is there any way for worker.CreateBackgroundServiceAsync<TService>() to resolve all dependencies of TService? I have tried passing the service provider around but with no luck. Unfortunately the code I need running in the background is quite large and has a lot of dependencies.

Thanks

**Comment by Tewr** [comment]
Hello. Well that would be very convenient but no it's not really that easy. dotnet gives me a list of assemblies, but no file names. Most of the time they are the same, but since .net5 just resolving the bcl is tricky, and there are loads of third party that won't follow this rule either. So until I find a better solution


 Resolving all dependencies is something which is done by the build process, and I don't interfer with that. All is done at run-time, and the needed dlls may have to be downloaded if I were to determine what file contains what assembly, which would be quite slow.

What could possibly be added would be just that feature: downloading and then loading *all* the files identifed by the build process into memory. Not very efficient nor fast, but indeed it works and this is what the initial versions of this library looked like. 

But determining what dependencies you need should be easy in most cases: just run worker.CreateBackgroundServiceAsync() and then call the different methods of your service, the missing types should turn up in the developer console.

**Comment by andersson09** [comment]
Thanks for the response. I might have phrased my question poorly. It was more to do with passing dependencies into the constructor of the worker service (not loading dlls) and having them resolved. Right now I can't inject anything other than httpclient.

**Comment by Tewr** [comment]
I see. You would like built in support for something like `ServiceCollection` from `Microsoft.Extensions.DependencyInjection`.

You could indeed accomplish this by creating a class called something like `TServiceFactory` and pass that rather than `TService`.

Then you would set up a singleton like this: 

ServiceCollection sc;
public MyService Resolve
    {
        //setup our DI, this part should be cached of course
if (sc is null)
        sc = new ServiceCollection()
            .AddSingleton<IFooService, FooService>()
            .AddSingleton<IMyService, MyService>()
            .BuildServiceProvider()
       
        return serviceProvider.GetService<TService>();

    }

Then you would have to call x.Resolve().MyMethod for each call. That part is hard to avoid without built in support for service factories. I'll think about some kind of built-in api for that...

**Comment by Tewr** [comment]
I don't want to get a dependency on a specific DI container in the core package, but I could possibly provide a dedicated extension package for Microsoft's DI container. That could also serve as an example for other DI containers

**Comment by andersson09** [comment]
Sounds good, a dedicated extension would be nice. Maybe a .UseStartup<StartUp> extension on WorkerInitOptions where we can create our own start up class with DI service collection registration

Another option to get it working with existing code is to create the service collection within the constructor. 

    public class WorkerFunction
    {
        private readonly IService service;
		
        public WorkerFunction()
        {
            var services = new ServiceCollection();
            services.AddSingleton<IService, Service>();

            var provider = services.BuildServiceProvider();
            service = provider.GetRequiredService<IService>();
        }

        public async Task<int> Run()
        {
            return await service.Run();
        }
    }

**Comment by Tewr** [comment]
Yes your method works fine if the service only exposes a single function, so it can easily be exposed in the factory class (your factory being called "WorkerFunction" here.). Its worse if the service has a lot of functions I guess.
