### ISSUE TITLE
Managing App State with Service Workers in Blazor WASM

### ISSUE THREAD

**Issue by dmarsh12** [Tewr/BlazorWorker#62]
Hi there!

I was directed to this package from a Reddit thread (https://www.reddit.com/r/Blazor/comments/ndpd6s/how_to_persist_state_across_multiple_browser_tabs/) to manage state between browser tabs. Essentially, I have a Blazor WASM application (.NET Core Hosted) in which I'd like to open a new tab/window but persist the data to the new page. Is this possible with Service Workers? I know this is possible natively with Blazor Server but I need to use Blazor WASM for the client. 

Use Case: Load Customer on main page -> Open customer history in new window -> Customer History displayed. Currently, the app "resets" and when opening a new tab/window it is treated as a new application. 

Any insight into this would be much appreciated!

**Comment by Tewr** [comment]
Hello!

This library is based on [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), as opposed to service worker or shared web worker. I am guessing that you would be interested in the latter: shared web workers.

While rewriting this library to support shared web workers would certainly be possible, you would still need to deal with the fact that a new tab is a new application. 

The shared worker would already be loaded and ready --, but the worker does not contain the blazor framework. As it stands today, blazor cannot be easily run from a worker either.

So in any trivial case, you would have to create a new app and then use some IPC to deal with front-end state once it's loaded. I don't know your use case in detail, but unless you have very intense communication in mind between you new tab and your old tab, I'd choose something like indexedDB instead to share data.

**Comment by ElanHasson** [comment]
I can add that I have spent several days trying to load Blazor in a worker. It is non-trivial primarily because the blazor boot strap JS depends on DOM (window/document) objects which don't exist. 

I tried the route of faking those items but it just became too much. There is work on the Blazor WASM side in progress to allow for multiple blazor apps on the same page and other work that would end up decoupling this dependency.

In my quest for multiple "threads" in .Net WASM, I also tried Uno platform with pthread support. This was also non-trivial. I ended up abandoning hope for threading (true or synthetic)  in .Net WASM and opted to restructure my application to essentially turn the workers @Tewr made into more stateless processors, which makes sense as we are message passing to them.

I found that the best approach was a pool of stateless BlazorWorkers  for each service type (file downloader, IndexedDb Writer, IndexedDb searcher, etc).
